<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Companies.Shared\Companies.Shared.csproj" />
    <ProjectReference Include="..\Domain.Contracts\Domain.Contracts.csproj" />
  </ItemGroup>

</Project>
